name: flutter_project
description: "A new Flutter project."

# Mencegah publikasi ke pub.dev secara tidak sengaja.
publish_to: 'none'

# Versi aplikasi: formatnya adalah [major].[minor].[patch]+[build_number]
version: 1.0.0+1

# Versi SDK Dart yang didukung
environment:
  sdk: '>=3.4.0 <4.0.0'

# Dependensi utama
dependencies:
  flutter:
    sdk: flutter

  # Ikon bergaya iOS
  cupertino_icons: any

  # Manajemen state & routing
  get: ^4.6.6

  # Penyimpanan data lokal
  get_storage: ^2.1.1

  # Cache gambar dari jaringan
  cached_network_image: ^3.3.0

  # HTTP request
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter untuk memastikan praktik coding yang baik
  flutter_lints: ^3.0.0

# Konfigurasi spesifik untuk Flutter
flutter:
  uses-material-design: true

  # Menambahkan aset gambar ke aplikasi
  assets:
    - assets/images/eren.png
    - assets/images/bayu.jpeg
    - assets/images/armor_titan.jpg
    - assets/images/attack_titan.jpg
    - assets/images/beast_titan.jpg
